name: catkin_lint
method: http://ppa.launchpad.net/roehling/ros/ubuntu
suites: [bionic, focal]
component: main
architectures: [i386, amd64, armhf, arm64, source]
filter_formula: (Package (= catkin-lint) | $Source (= catkin-lint)), $Version (% 1.6.14-*)
