name: catkinlint
method: http://ppa.launchpad.net/roehling/latest/ubuntu
suites: [precise, quantal, raring, saucy, trusty]
component: main
architectures: [i386, amd64, source]
filter_formula: Package (== catkin-lint ) | Package (== python-catkin-lint)
