name: colladadomppa
#Switching to testing for newer colladadom
#method: http://ppa.launchpad.net/openrave/release/ubuntu
#suites: [lucid, maverick, natty, oneiric, precise, quantal, raring, saucy, trusty]
method: http://ppa.launchpad.net/openrave/testing/ubuntu
suites: [saucy, trusty, utopic, vivid, wily]
component: main
architectures: [i386, amd64, armhf, arm64, source]
filter_formula: Package (% *collada-dom* )
