name: ignition_citadel_gazebo11_ubuntu_focal
method: http://packages.osrfoundation.org/gazebo/ubuntu-stable
suites: [focal]
component: main
architectures: [amd64, armhf, arm64, source]
filter_formula: "\
(Package (= gazebo11) |\
 Package (= gazebo11-common) |\
 Package (= gazebo11-dbg) |\
 Package (= gazebo11-doc) |\
 Package (= gazebo11-plugin-base) |\
 Package (= libgazebo11) |\
 Package (= libgazebo11-dev) \
), $Version (% 11.15.1-1*) |\
(Package (= gz-citadel) |\
 Package (= ignition-citadel) \
), $Version (% 1.0.2-2*) |\
(Package (= ignition-cmake2) |\
 Package (= libgz-cmake2-dev) |\
 Package (= libignition-cmake2-dev) \
), $Version (% 2.15.0-1*) |\
(Package (= ignition-common3) |\
 Package (= libgz-common3) |\
 Package (= libgz-common3-av) |\
 Package (= libgz-common3-av-dev) |\
 Package (= libgz-common3-core-dev) |\
 Package (= libgz-common3-dev) |\
 Package (= libgz-common3-events) |\
 Package (= libgz-common3-events-dev) |\
 Package (= libgz-common3-graphics) |\
 Package (= libgz-common3-graphics-dev) |\
 Package (= libgz-common3-profiler) |\
 Package (= libgz-common3-profiler-dev) |\
 Package (= libignition-common3) |\
 Package (= libignition-common3-av) |\
 Package (= libignition-common3-av-dev) |\
 Package (= libignition-common3-core-dev) |\
 Package (= libignition-common3-dev) |\
 Package (= libignition-common3-events) |\
 Package (= libignition-common3-events-dev) |\
 Package (= libignition-common3-graphics) |\
 Package (= libignition-common3-graphics-dev) |\
 Package (= libignition-common3-profiler) |\
 Package (= libignition-common3-profiler-dev) \
), $Version (% 3.14.2-1*) |\
(Package (= ignition-fuel-tools4) |\
 Package (= libgz-fuel-tools4) |\
 Package (= libgz-fuel-tools4-dev) |\
 Package (= libignition-fuel-tools4) |\
 Package (= libignition-fuel-tools4-dev) \
), $Version (% 4.9.1-1*) |\
(Package (= ignition-gazebo3) |\
 Package (= libgz-sim3) |\
 Package (= libgz-sim3-dbg) |\
 Package (= libgz-sim3-dev) |\
 Package (= libgz-sim3-plugins) |\
 Package (= libignition-gazebo3) |\
 Package (= libignition-gazebo3-dbg) |\
 Package (= libignition-gazebo3-dev) |\
 Package (= libignition-gazebo3-plugins) \
), $Version (% 3.14.0-1*) |\
(Package (= ignition-gui3) |\
 Package (= libgz-gui3) |\
 Package (= libgz-gui3-dev) |\
 Package (= libignition-gui3) |\
 Package (= libignition-gui3-dev) \
), $Version (% 3.12.0-1*) |\
(Package (= ignition-launch2) |\
 Package (= libgz-launch2) |\
 Package (= libgz-launch2-dev) |\
 Package (= libignition-launch2) |\
 Package (= libignition-launch2-dev) \
), $Version (% 2.3.0-1*) |\
(Package (= ignition-math6) |\
 Package (= libgz-math6) |\
 Package (= libgz-math6-dbg) |\
 Package (= libgz-math6-dev) |\
 Package (= libgz-math6-eigen3-dev) |\
 Package (= libignition-math6) |\
 Package (= libignition-math6-dbg) |\
 Package (= libignition-math6-dev) |\
 Package (= libignition-math6-eigen3-dev) |\
 Package (= python3-gz-math6) |\
 Package (= python3-ignition-math6) |\
 Package (= ruby-gz-math6) |\
 Package (= ruby-ignition-math6) \
), $Version (% 6.13.0-1*) |\
(Package (= ignition-msgs5) |\
 Package (= libgz-msgs5) |\
 Package (= libgz-msgs5-dev) |\
 Package (= libignition-msgs5) |\
 Package (= libignition-msgs5-dev) \
), $Version (% 5.10.0-4*) |\
(Package (= ignition-physics2) |\
 Package (= libgz-physics2) |\
 Package (= libgz-physics2-core-dev) |\
 Package (= libgz-physics2-dartsim) |\
 Package (= libgz-physics2-dartsim-dev) |\
 Package (= libgz-physics2-dev) |\
 Package (= libgz-physics2-mesh-dev) |\
 Package (= libgz-physics2-sdf-dev) |\
 Package (= libgz-physics2-tpe) |\
 Package (= libgz-physics2-tpe-dev) |\
 Package (= libgz-physics2-tpelib) |\
 Package (= libgz-physics2-tpelib-dev) |\
 Package (= libignition-physics2) |\
 Package (= libignition-physics2-core-dev) |\
 Package (= libignition-physics2-dartsim) |\
 Package (= libignition-physics2-dartsim-dev) |\
 Package (= libignition-physics2-dev) |\
 Package (= libignition-physics2-mesh-dev) |\
 Package (= libignition-physics2-sdf-dev) |\
 Package (= libignition-physics2-tpe) |\
 Package (= libignition-physics2-tpe-dev) |\
 Package (= libignition-physics2-tpelib) |\
 Package (= libignition-physics2-tpelib-dev) \
), $Version (% 2.5.1-1*) |\
(Package (= ignition-plugin) |\
 Package (= libgz-plugin) |\
 Package (= libgz-plugin-dbg) |\
 Package (= libgz-plugin-dev) |\
 Package (= libignition-plugin) |\
 Package (= libignition-plugin-dbg) |\
 Package (= libignition-plugin-dev) \
), $Version (% 1.3.0-1*) |\
(Package (= ignition-rendering3) |\
 Package (= libgz-rendering3) |\
 Package (= libgz-rendering3-core-dev) |\
 Package (= libgz-rendering3-dev) |\
 Package (= libgz-rendering3-ogre1) |\
 Package (= libgz-rendering3-ogre1-dev) |\
 Package (= libgz-rendering3-ogre2) |\
 Package (= libgz-rendering3-ogre2-dev) |\
 Package (= libignition-rendering3) |\
 Package (= libignition-rendering3-core-dev) |\
 Package (= libignition-rendering3-dev) |\
 Package (= libignition-rendering3-ogre1) |\
 Package (= libignition-rendering3-ogre1-dev) |\
 Package (= libignition-rendering3-ogre2) |\
 Package (= libignition-rendering3-ogre2-dev) \
), $Version (% 3.6.0-5*) |\
(Package (= ignition-sensors3) |\
 Package (= libgz-sensors3) |\
 Package (= libgz-sensors3-air-pressure) |\
 Package (= libgz-sensors3-air-pressure-dev) |\
 Package (= libgz-sensors3-altimeter) |\
 Package (= libgz-sensors3-altimeter-dev) |\
 Package (= libgz-sensors3-camera) |\
 Package (= libgz-sensors3-camera-dev) |\
 Package (= libgz-sensors3-core-dev) |\
 Package (= libgz-sensors3-depth-camera) |\
 Package (= libgz-sensors3-depth-camera-dev) |\
 Package (= libgz-sensors3-dev) |\
 Package (= libgz-sensors3-gpu-lidar) |\
 Package (= libgz-sensors3-gpu-lidar-dev) |\
 Package (= libgz-sensors3-imu) |\
 Package (= libgz-sensors3-imu-dev) |\
 Package (= libgz-sensors3-lidar) |\
 Package (= libgz-sensors3-lidar-dev) |\
 Package (= libgz-sensors3-logical-camera) |\
 Package (= libgz-sensors3-logical-camera-dev) |\
 Package (= libgz-sensors3-magnetometer) |\
 Package (= libgz-sensors3-magnetometer-dev) |\
 Package (= libgz-sensors3-rendering) |\
 Package (= libgz-sensors3-rendering-dev) |\
 Package (= libgz-sensors3-rgbd-camera) |\
 Package (= libgz-sensors3-rgbd-camera-dev) |\
 Package (= libgz-sensors3-thermal-camera) |\
 Package (= libgz-sensors3-thermal-camera-dev) |\
 Package (= libignition-sensors3) |\
 Package (= libignition-sensors3-air-pressure) |\
 Package (= libignition-sensors3-air-pressure-dev) |\
 Package (= libignition-sensors3-altimeter) |\
 Package (= libignition-sensors3-altimeter-dev) |\
 Package (= libignition-sensors3-camera) |\
 Package (= libignition-sensors3-camera-dev) |\
 Package (= libignition-sensors3-core-dev) |\
 Package (= libignition-sensors3-depth-camera) |\
 Package (= libignition-sensors3-depth-camera-dev) |\
 Package (= libignition-sensors3-dev) |\
 Package (= libignition-sensors3-gpu-lidar) |\
 Package (= libignition-sensors3-gpu-lidar-dev) |\
 Package (= libignition-sensors3-imu) |\
 Package (= libignition-sensors3-imu-dev) |\
 Package (= libignition-sensors3-lidar) |\
 Package (= libignition-sensors3-lidar-dev) |\
 Package (= libignition-sensors3-logical-camera) |\
 Package (= libignition-sensors3-logical-camera-dev) |\
 Package (= libignition-sensors3-magnetometer) |\
 Package (= libignition-sensors3-magnetometer-dev) |\
 Package (= libignition-sensors3-rendering) |\
 Package (= libignition-sensors3-rendering-dev) |\
 Package (= libignition-sensors3-rgbd-camera) |\
 Package (= libignition-sensors3-rgbd-camera-dev) |\
 Package (= libignition-sensors3-thermal-camera) |\
 Package (= libignition-sensors3-thermal-camera-dev) \
), $Version (% 3.4.0-1*) |\
(Package (= gz-tools) |\
 Package (= ignition-tools) |\
 Package (= libgz-tools-dev) |\
 Package (= libignition-tools-dev) \
), $Version (% 1.5.0-1*) |\
(Package (= ignition-transport8) |\
 Package (= libgz-transport8) |\
 Package (= libgz-transport8-core-dev) |\
 Package (= libgz-transport8-dbg) |\
 Package (= libgz-transport8-dev) |\
 Package (= libgz-transport8-log) |\
 Package (= libgz-transport8-log-dev) |\
 Package (= libignition-transport8) |\
 Package (= libignition-transport8-core-dev) |\
 Package (= libignition-transport8-dbg) |\
 Package (= libignition-transport8-dev) |\
 Package (= libignition-transport8-log) |\
 Package (= libignition-transport8-log-dev) \
), $Version (% 8.5.0-1*) |\
(Package (= ogre-2.1) |\
 Package (= blender-ogrexml-2.1) |\
 Package (= libogre-2.1) |\
 Package (= libogre-2.1-dev) |\
 Package (= ogre-2.1-doc) |\
 Package (= ogre-2.1-tools) \
), $Version (% 2.0.9999~20180616~06a386f-3*) |\
(Package (= sdformat9) |\
 Package (= libsdformat9) |\
 Package (= libsdformat9-dbg) |\
 Package (= libsdformat9-dev) |\
 Package (= sdformat9-doc) |\
 Package (= sdformat9-sdf) \
), $Version (% 9.8.0-1*) \
"
