name: ignition_fortress_ubuntu_focal
method: http://packages.osrfoundation.org/gazebo/ubuntu-stable
suites: [focal]
component: main
architectures: [amd64, armhf, arm64, source]
filter_formula: "\
(Package (= gz-fortress) |\
 Package (= ignition-fortress) \
), $Version (% 1.0.3-2*) |\
(Package (= ignition-common4) |\
 Package (= libgz-common4) |\
 Package (= libgz-common4-av) |\
 Package (= libgz-common4-av-dev) |\
 Package (= libgz-common4-core-dev) |\
 Package (= libgz-common4-dev) |\
 Package (= libgz-common4-events) |\
 Package (= libgz-common4-events-dev) |\
 Package (= libgz-common4-graphics) |\
 Package (= libgz-common4-graphics-dev) |\
 Package (= libgz-common4-profiler) |\
 Package (= libgz-common4-profiler-dev) |\
 Package (= libignition-common4) |\
 Package (= libignition-common4-av) |\
 Package (= libignition-common4-av-dev) |\
 Package (= libignition-common4-core-dev) |\
 Package (= libignition-common4-dev) |\
 Package (= libignition-common4-events) |\
 Package (= libignition-common4-events-dev) |\
 Package (= libignition-common4-graphics) |\
 Package (= libignition-common4-graphics-dev) |\
 Package (= libignition-common4-profiler) |\
 Package (= libignition-common4-profiler-dev) \
), $Version (% 4.5.2-1*) |\
(Package (= ignition-fuel-tools7) |\
 Package (= libgz-fuel-tools7) |\
 Package (= libgz-fuel-tools7-dev) |\
 Package (= libignition-fuel-tools7) |\
 Package (= libignition-fuel-tools7-dev) \
), $Version (% 7.1.0-1*) |\
(Package (= ignition-gazebo6) |\
 Package (= libgz-sim6) |\
 Package (= libgz-sim6-dbg) |\
 Package (= libgz-sim6-dev) |\
 Package (= libgz-sim6-plugins) |\
 Package (= libignition-gazebo6) |\
 Package (= libignition-gazebo6-dbg) |\
 Package (= libignition-gazebo6-dev) |\
 Package (= libignition-gazebo6-plugins) |\
 Package (= python3-gz-sim6) \
 Package (= python3-ignition-gazebo6) \
), $Version (% 6.11.0-2*) |\
(Package (= ignition-gui6) |\
 Package (= libgz-gui6) |\
 Package (= libgz-gui6-dev) |\
 Package (= libignition-gui6) |\
 Package (= libignition-gui6-dev) \
), $Version (% 6.6.1-2*) |\
(Package (= ignition-launch5) |\
 Package (= libgz-launch5) |\
 Package (= libgz-launch5-dev) |\
 Package (= libignition-launch5) |\
 Package (= libignition-launch5-dev) \
), $Version (% 5.2.0-1*) |\
(Package (= ignition-msgs8) |\
 Package (= libgz-msgs8) |\
 Package (= libgz-msgs8-dev) |\
 Package (= libignition-msgs8) |\
 Package (= libignition-msgs8-dev) \
), $Version (% 8.6.0-3*) |\
(Package (= ignition-physics5) |\
 Package (= libgz-physics5) |\
 Package (= libgz-physics5-bullet) |\
 Package (= libgz-physics5-bullet-dev) |\
 Package (= libgz-physics5-core-dev) |\
 Package (= libgz-physics5-dartsim) |\
 Package (= libgz-physics5-dartsim-dev) |\
 Package (= libgz-physics5-dev) |\
 Package (= libgz-physics5-heightmap-dev) |\
 Package (= libgz-physics5-mesh-dev) |\
 Package (= libgz-physics5-sdf-dev) |\
 Package (= libgz-physics5-tpe) |\
 Package (= libgz-physics5-tpe-dev) |\
 Package (= libgz-physics5-tpelib) |\
 Package (= libgz-physics5-tpelib-dev) |\
 Package (= libignition-physics5) |\
 Package (= libignition-physics5-bullet) |\
 Package (= libignition-physics5-bullet-dev) |\
 Package (= libignition-physics5-core-dev) |\
 Package (= libignition-physics5-dartsim) |\
 Package (= libignition-physics5-dartsim-dev) |\
 Package (= libignition-physics5-dev) |\
 Package (= libignition-physics5-heightmap-dev) |\
 Package (= libignition-physics5-mesh-dev) |\
 Package (= libignition-physics5-sdf-dev) |\
 Package (= libignition-physics5-tpe) |\
 Package (= libignition-physics5-tpe-dev) |\
 Package (= libignition-physics5-tpelib) |\
 Package (= libignition-physics5-tpelib-dev) \
), $Version (% 5.2.0-2*) |\
(Package (= ignition-rendering6) |\
 Package (= libgz-rendering6) |\
 Package (= libgz-rendering6-core-dev) |\
 Package (= libgz-rendering6-dev) |\
 Package (= libgz-rendering6-ogre1) |\
 Package (= libgz-rendering6-ogre1-dev) |\
 Package (= libgz-rendering6-ogre2) |\
 Package (= libgz-rendering6-ogre2-dev) |\
 Package (= libignition-rendering6) |\
 Package (= libignition-rendering6-core-dev) |\
 Package (= libignition-rendering6-dev) |\
 Package (= libignition-rendering6-ogre1) |\
 Package (= libignition-rendering6-ogre1-dev) |\
 Package (= libignition-rendering6-ogre2) |\
 Package (= libignition-rendering6-ogre2-dev) \
), $Version (% 6.5.1-2*) |\
(Package (= ignition-sensors6) |\
 Package (= libgz-sensors6) |\
 Package (= libgz-sensors6-air-pressure) |\
 Package (= libgz-sensors6-air-pressure-dev) |\
 Package (= libgz-sensors6-altimeter) |\
 Package (= libgz-sensors6-altimeter-dev) |\
 Package (= libgz-sensors6-camera) |\
 Package (= libgz-sensors6-camera-dev) |\
 Package (= libgz-sensors6-core-dev) |\
 Package (= libgz-sensors6-depth-camera) |\
 Package (= libgz-sensors6-depth-camera-dev) |\
 Package (= libgz-sensors6-dev) |\
 Package (= libgz-sensors6-force-torque) |\
 Package (= libgz-sensors6-force-torque-dev) |\
 Package (= libgz-sensors6-gpu-lidar) |\
 Package (= libgz-sensors6-gpu-lidar-dev) |\
 Package (= libgz-sensors6-imu) |\
 Package (= libgz-sensors6-imu-dev) |\
 Package (= libgz-sensors6-lidar) |\
 Package (= libgz-sensors6-lidar-dev) |\
 Package (= libgz-sensors6-logical-camera) |\
 Package (= libgz-sensors6-logical-camera-dev) |\
 Package (= libgz-sensors6-magnetometer) |\
 Package (= libgz-sensors6-magnetometer-dev) |\
 Package (= libgz-sensors6-navsat) |\
 Package (= libgz-sensors6-navsat-dev) |\
 Package (= libgz-sensors6-rendering) |\
 Package (= libgz-sensors6-rendering-dev) |\
 Package (= libgz-sensors6-rgbd-camera) |\
 Package (= libgz-sensors6-rgbd-camera-dev) |\
 Package (= libgz-sensors6-segmentation-camera) |\
 Package (= libgz-sensors6-segmentation-camera-dev) |\
 Package (= libgz-sensors6-thermal-camera) |\
 Package (= libgz-sensors6-thermal-camera-dev) |\
 Package (= libignition-sensors6) |\
 Package (= libignition-sensors6-air-pressure) |\
 Package (= libignition-sensors6-air-pressure-dev) |\
 Package (= libignition-sensors6-altimeter) |\
 Package (= libignition-sensors6-altimeter-dev) |\
 Package (= libignition-sensors6-camera) |\
 Package (= libignition-sensors6-camera-dev) |\
 Package (= libignition-sensors6-core-dev) |\
 Package (= libignition-sensors6-depth-camera) |\
 Package (= libignition-sensors6-depth-camera-dev) |\
 Package (= libignition-sensors6-dev) |\
 Package (= libignition-sensors6-force-torque) |\
 Package (= libignition-sensors6-force-torque-dev) |\
 Package (= libignition-sensors6-gpu-lidar) |\
 Package (= libignition-sensors6-gpu-lidar-dev) |\
 Package (= libignition-sensors6-imu) |\
 Package (= libignition-sensors6-imu-dev) |\
 Package (= libignition-sensors6-lidar) |\
 Package (= libignition-sensors6-lidar-dev) |\
 Package (= libignition-sensors6-logical-camera) |\
 Package (= libignition-sensors6-logical-camera-dev) |\
 Package (= libignition-sensors6-magnetometer) |\
 Package (= libignition-sensors6-magnetometer-dev) |\
 Package (= libignition-sensors6-navsat) |\
 Package (= libignition-sensors6-navsat-dev) |\
 Package (= libignition-sensors6-rendering) |\
 Package (= libignition-sensors6-rendering-dev) |\
 Package (= libignition-sensors6-rgbd-camera) |\
 Package (= libignition-sensors6-rgbd-camera-dev) |\
 Package (= libignition-sensors6-segmentation-camera) |\
 Package (= libignition-sensors6-segmentation-camera-dev) |\
 Package (= libignition-sensors6-thermal-camera) |\
 Package (= libignition-sensors6-thermal-camera-dev) \
), $Version (% 6.6.0-3*) |\
(Package (= ignition-transport11) |\
 Package (= libgz-transport11) |\
 Package (= libgz-transport11-core-dev) |\
 Package (= libgz-transport11-dbg) |\
 Package (= libgz-transport11-dev) |\
 Package (= libgz-transport11-log) |\
 Package (= libgz-transport11-log-dev) |\
 Package (= libignition-transport11) |\
 Package (= libignition-transport11-core-dev) |\
 Package (= libignition-transport11-dbg) |\
 Package (= libignition-transport11-dev) |\
 Package (= libignition-transport11-log) |\
 Package (= libignition-transport11-log-dev) \
), $Version (% 11.2.0-3*) |\
(Package (= ignition-utils1) |\
 Package (= libgz-utils1) |\
 Package (= libgz-utils1-cli-dev) |\
 Package (= libgz-utils1-dbg) |\
 Package (= libgz-utils1-dev) |\
 Package (= libignition-utils1) |\
 Package (= libignition-utils1-cli-dev) |\
 Package (= libignition-utils1-dbg) |\
 Package (= libignition-utils1-dev) \
), $Version (% 1.4.0-2*) |\
(Package (= ogre-2.2) |\
 Package (= blender-ogrexml-2.2) |\
 Package (= libogre-2.2) |\
 Package (= libogre-2.2-dev) |\
 Package (= ogre-2.2-doc) |\
 Package (= ogre-2.2-tools) \
), $Version (% 2.2.5+20210824~ec3f70c-4*) |\
(Package (= sdformat12) |\
 Package (= libsdformat12) |\
 Package (= libsdformat12-dbg) |\
 Package (= libsdformat12-dev) |\
 Package (= sdformat12-doc) |\
 Package (= sdformat12-sdf) \
), $Version (% 12.5.0-1*) \
"
