name: ignition_citadel_gazebo11_ubuntu_focal
method: http://packages.osrfoundation.org/gazebo/ubuntu-stable
suites: [focal]
component: main
architectures: [amd64, armhf, arm64, source]
filter_formula: "\
(Package (= gazebo11) |\
 Package (= gazebo11-common) |\
 Package (= gazebo11-dbg) |\
 Package (= gazebo11-doc) |\
 Package (= gazebo11-plugin-base) |\
 Package (= libgazebo11) |\
 Package (= libgazebo11-dev) \
), $Version (% 11.10.2-1*) |\
(Package (= ignition-citadel) \
), $Version (% 1.0.2-1*) |\
(Package (= ignition-cmake2) |\
 Package (= libignition-cmake2-dev) \
), $Version (% 2.12.1-1*) |\
(Package (= ignition-common4) |\
 Package (= libignition-common4) |\
 Package (= libignition-common4-av) |\
 Package (= libignition-common4-av-dev) |\
 Package (= libignition-common4-core-dev) |\
 Package (= libignition-common4-dev) |\
 Package (= libignition-common4-events) |\
 Package (= libignition-common4-events-dev) |\
 Package (= libignition-common4-graphics) |\
 Package (= libignition-common4-graphics-dev) |\
 Package (= libignition-common4-profiler) |\
 Package (= libignition-common4-profiler-dev) \
), $Version (% 4.5.0-1*) |\
(Package (= ignition-fuel-tools6) |\
 Package (= libignition-fuel-tools6) |\
 Package (= libignition-fuel-tools6-dev) \
), $Version (% 6.2.0-1*) |\
(Package (= ignition-gazebo5) |\
 Package (= libignition-gazebo5) |\
 Package (= libignition-gazebo5-dbg) |\
 Package (= libignition-gazebo5-dev) |\
 Package (= libignition-gazebo5-plugins) \
), $Version (% 5.4.0-1*) |\
(Package (= ignition-gui5) |\
 Package (= libignition-gui5) |\
 Package (= libignition-gui5-dev) \
), $Version (% 5.5.0-1*) |\
(Package (= ignition-launch4) |\
 Package (= libignition-launch4) |\
 Package (= libignition-launch4-dev) \
), $Version (% 4.1.0-1*) |\
(Package (= ignition-math6) |\
 Package (= libignition-math6) |\
 Package (= libignition-math6-dbg) |\
 Package (= libignition-math6-dev) |\
 Package (= libignition-math6-eigen3-dev) |\
 Package (= python3-ignition-math6) |\
 Package (= ruby-ignition-math6) \
), $Version (% 6.10.0-1*) |\
(Package (= ignition-msgs7) |\
 Package (= libignition-msgs7) |\
 Package (= libignition-msgs7-dev) \
), $Version (% 7.3.0-1*) |\
(Package (= ignition-physics4) |\
 Package (= libignition-physics4) |\
 Package (= libignition-physics4-bullet) |\
 Package (= libignition-physics4-bullet-dev) |\
 Package (= libignition-physics4-core-dev) |\
 Package (= libignition-physics4-dartsim) |\
 Package (= libignition-physics4-dartsim-dev) |\
 Package (= libignition-physics4-dev) |\
 Package (= libignition-physics4-heightmap-dev) |\
 Package (= libignition-physics4-mesh-dev) |\
 Package (= libignition-physics4-sdf-dev) |\
 Package (= libignition-physics4-tpe) |\
 Package (= libignition-physics4-tpe-dev) |\
 Package (= libignition-physics4-tpelib) |\
 Package (= libignition-physics4-tpelib-dev) \
), $Version (% 4.3.0-1*) |\
(Package (= ignition-rendering5) |\
 Package (= libignition-rendering5) |\
 Package (= libignition-rendering5-core-dev) |\
 Package (= libignition-rendering5-dev) |\
 Package (= libignition-rendering5-ogre1) |\
 Package (= libignition-rendering5-ogre1-dev) |\
 Package (= libignition-rendering5-ogre2) |\
 Package (= libignition-rendering5-ogre2-dev) \
), $Version (% 5.2.1-1*) |\
(Package (= ignition-sensors5) |\
 Package (= libignition-sensors5) |\
 Package (= libignition-sensors5-air-pressure) |\
 Package (= libignition-sensors5-air-pressure-dev) |\
 Package (= libignition-sensors5-altimeter) |\
 Package (= libignition-sensors5-altimeter-dev) |\
 Package (= libignition-sensors5-camera) |\
 Package (= libignition-sensors5-camera-dev) |\
 Package (= libignition-sensors5-core-dev) |\
 Package (= libignition-sensors5-depth-camera) |\
 Package (= libignition-sensors5-depth-camera-dev) |\
 Package (= libignition-sensors5-dev) |\
 Package (= libignition-sensors5-gpu-lidar) |\
 Package (= libignition-sensors5-gpu-lidar-dev) |\
 Package (= libignition-sensors5-imu) |\
 Package (= libignition-sensors5-imu-dev) |\
 Package (= libignition-sensors5-lidar) |\
 Package (= libignition-sensors5-lidar-dev) |\
 Package (= libignition-sensors5-logical-camera) |\
 Package (= libignition-sensors5-logical-camera-dev) |\
 Package (= libignition-sensors5-magnetometer) |\
 Package (= libignition-sensors5-magnetometer-dev) |\
 Package (= libignition-sensors5-rendering) |\
 Package (= libignition-sensors5-rendering-dev) |\
 Package (= libignition-sensors5-rgbd-camera) |\
 Package (= libignition-sensors5-rgbd-camera-dev) |\
 Package (= libignition-sensors5-thermal-camera) |\
 Package (= libignition-sensors5-thermal-camera-dev) \
), $Version (% 5.1.1-1*) |\
(Package (= ignition-transport10) |\
 Package (= libignition-transport10) |\
 Package (= libignition-transport10-core-dev) |\
 Package (= libignition-transport10-dbg) |\
 Package (= libignition-transport10-dev) |\
 Package (= libignition-transport10-log) |\
 Package (= libignition-transport10-log-dev) \
), $Version (% 10.2.0-1*) |\
(Package (= ignition-utils1) |\
 Package (= libignition-utils1) |\
 Package (= libignition-utils1-cli-dev) |\
 Package (= libignition-utils1-dbg) |\
 Package (= libignition-utils1-dev) \
), $Version (% 1.4.0-1*) |\
(Package (= ogre-2.2) |\
 Package (= blender-ogrexml-2.2) |\
 Package (= libogre-2.2) |\
 Package (= libogre-2.2-dev) |\
 Package (= ogre-2.2-doc) |\
 Package (= ogre-2.2-tools) \
), $Version (% 2.2.5+20210824~ec3f70c-4*) |\
(Package (= sdformat11) |\
 Package (= libsdformat11) |\
 Package (= libsdformat11-dbg) |\
 Package (= libsdformat11-dev) |\
 Package (= sdformat11-doc) |\
 Package (= sdformat11-sdf) \
), $Version (% 11.4.1-1*) \
"
