name: ignition_focal_source
method: http://packages.osrfoundation.org/gazebo/ubuntu-stable
suites: [focal]
component: main
architectures: [amd64, i386, armhf, arm64, source]
filter_formula: "\
((Package (% =gazebo11) |\
Package (% =gazebo11-common) |\
Package (% =gazebo11-dbg) |\
Package (% =gazebo11-doc) |\
Package (% =libgazebo11) |\
Package (% =libgazebo11-dev)), \
$Version (% 11.3.0-1~focal)) |\
(Package (% =ignition-cmake2), $Version (% 2.6.2-1~focal)) |\
(Package (% =ignition-common3), $Version (% 3.11.1-1~focal)) |\
((Package (% =libignition-common3) |\
Package (% =libignition-common3-av) |\
Package (% =libignition-common3-av-dev) |\
Package (% =libignition-common3-core-dev) |\
Package (% =libignition-common3-dev) |\
Package (% =libignition-common3-events) |\
Package (% =libignition-common3-events-dev) |\
Package (% =libignition-common3-graphics) |\
Package (% =libignition-common3-graphics-dev) |\
Package (% =libignition-common3-profiler) |\
Package (% =libignition-common3-profiler-dev)), \
$Version (% 3.11.1-1~focal)) |\
(Package (% =ignition-fuel-tools4), $Version (% 4.3.0-1~focal)) |\
((Package (% =ignition-gazebo3) |\
Package (% =libignition-gazebo3) |\
Package (% =libignition-gazebo3-dev) |\
Package (% =libignition-gazebo3-plugins)), \
$Version (% 3.8.0-1~focal)) |\
(Package (% =ignition-gui3), $Version (% 3.4.0-1~focal)) |\
((Package (% =ignition-launch2) |\
Package (% =libignition-launch2) |\
Package (% =libignition-launch2-dev)), \
$Version (% 2.2.1-1~focal)) |\
(Package (% =ignition-math6), $Version (% 6.7.0-1~focal)) |\
(Package (% =ignition-msgs5), $Version (% 5.6.0-1~focal)) |\
(Package (% =ignition-physics2), $Version (% 2.3.0-1~focal)) |\
(Package (% =ignition-plugin), $Version (% 1.1.0-1~focal)) |\
((Package (% =ignition-rendering3) |\
Package (% =libignition-rendering3) |\
Package (% =libignition-rendering3-core-dev) |\
Package (% =libignition-rendering3-dev) |\
Package (% =libignition-rendering3-ogre1) |\
Package (% =libignition-rendering3-ogre1-dev) |\
Package (% =libignition-rendering3-ogre2) |\
Package (% =libignition-rendering3-ogre2-dev)), \
$Version (% 3.4.0-1~focal)) |\
((Package (% =ignition-sensors3) |\
Package (% =libignition-sensors3) |\
Package (% =libignition-sensors3-air-pressure) |\
Package (% =libignition-sensors3-air-pressure-dev) |\
Package (% =libignition-sensors3-altimeter) |\
Package (% =libignition-sensors3-altimeter-dev) |\
Package (% =libignition-sensors3-camera) |\
Package (% =libignition-sensors3-camera-dev) |\
Package (% =libignition-sensors3-core-dev) |\
Package (% =libignition-sensors3-depth-camera) |\
Package (% =libignition-sensors3-depth-camera-dev) |\
Package (% =libignition-sensors3-dev) |\
Package (% =libignition-sensors3-gpu-lidar) |\
Package (% =libignition-sensors3-gpu-lidar-dev) |\
Package (% =libignition-sensors3-imu) |\
Package (% =libignition-sensors3-imu-dev) |\
Package (% =libignition-sensors3-lidar) |\
Package (% =libignition-sensors3-lidar-dev) |\
Package (% =libignition-sensors3-logical-camera) |\
Package (% =libignition-sensors3-logical-camera-dev) |\
Package (% =libignition-sensors3-magnetometer) |\
Package (% =libignition-sensors3-magnetometer-dev) |\
Package (% =libignition-sensors3-rendering) |\
Package (% =libignition-sensors3-rendering-dev) |\
Package (% =libignition-sensors3-rgbd-camera) |\
Package (% =libignition-sensors3-rgbd-camera-dev) |\
Package (% =libignition-sensors3-thermal-camera) |\
Package (% =libignition-sensors3-thermal-camera-dev)), \
$Version (% 3.2.0-1~focal)) |\
(Package (% =ignition-transport8), $Version (% 8.2.0-1~focal)) |\
((Package (% =ogre-2.1) |\
Package (% =libogre-2.1) |\
Package (% =libogre-2.1-dev)),
$Version (% 2.0.9999~20180616~06a386f-3osrf~focal)) |\
((Package (% =sdformat9) |\
Package (% =libsdformat9) |\
Package (% =libsdformat9-dbg) |\
Package (% =libsdformat9-dev) |\
Package (% =sdformat9-doc) |\
Package (% =sdformat9-sdf)), \
$Version (% 9.5.0-1~focal)) \
"
