name: ignition_citadel_gazebo11_debian_buster.yaml
method: http://packages.osrfoundation.org/gazebo/debian-stable
suites: [buster]
component: main
architectures: [amd64, source]
filter_formula: "\
(Package (% gazebo11), $Version (% 11.5.0*))|\
(Package (% gazebo11-common), $Version (% 11.5.0*))|\
(Package (% gazebo11-dbg), $Version (% 11.5.0*))|\
(Package (% gazebo11-doc), $Version (% 11.5.0*))|\
(Package (% gazebo11-plugin-base), $Version (% 11.5.0*))|\
(Package (% ignition-citadel), $Version (% 1.0.0*))|\
(Package (% ignition-tools), $Version (% 1.2.0*))|\
(Package (% libgazebo11), $Version (% 11.5.0*))|\
(Package (% libgazebo11-dev), $Version (% 11.5.0*))|\
(Package (% libignition-cmake2-dev), $Version (% 2.7.0*))|\
(Package (% libignition-common3), $Version (% 3.12.0*))|\
(Package (% libignition-common3-av), $Version (% 3.12.0*))|\
(Package (% libignition-common3-av-dev), $Version (% 3.12.0*))|\
(Package (% libignition-common3-core-dev), $Version (% 3.12.0*))|\
(Package (% libignition-common3-dev), $Version (% 3.12.0*))|\
(Package (% libignition-common3-events), $Version (% 3.12.0*))|\
(Package (% libignition-common3-events-dev), $Version (% 3.12.0*))|\
(Package (% libignition-common3-graphics), $Version (% 3.12.0*))|\
(Package (% libignition-common3-graphics-dev), $Version (% 3.12.0*))|\
(Package (% libignition-common3-profiler), $Version (% 3.12.0*))|\
(Package (% libignition-common3-profiler-dev), $Version (% 3.12.0*))|\
(Package (% libignition-fuel-tools4), $Version (% 4.3.0*))|\
(Package (% libignition-fuel-tools4-dev), $Version (% 4.3.0*))|\
(Package (% libignition-gazebo3), $Version (% 3.0.0*))|\
(Package (% libignition-gazebo3-dev), $Version (% 3.0.0*))|\
(Package (% libignition-gazebo3-plugins), $Version (% 3.0.0*))|\
(Package (% libignition-gui3), $Version (% 3.5.1*))|\
(Package (% libignition-gui3-dev), $Version (% 3.5.1*))|\
(Package (% libignition-launch2), $Version (% 2.0.1*))|\
(Package (% libignition-launch2-dev), $Version (% 2.0.1*))|\
(Package (% libignition-math6), $Version (% 6.8.0*))|\
(Package (% libignition-math6-dbg), $Version (% 6.8.0*))|\
(Package (% libignition-math6-dev), $Version (% 6.8.0*))|\
(Package (% libignition-math6-eigen3-dev), $Version (% 6.8.0*))|\
(Package (% libignition-msgs5), $Version (% 5.7.0*))|\
(Package (% libignition-msgs5-dbg), $Version (% 5.7.0*))|\
(Package (% libignition-msgs5-dev), $Version (% 5.7.0*))|\
(Package (% libignition-physics2), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-core-dev), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-dartsim), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-dartsim-dev), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-dev), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-mesh-dev), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-sdf-dev), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-tpe), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-tpe-dev), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-tpelib), $Version (% 2.4.0*))|\
(Package (% libignition-physics2-tpelib-dev), $Version (% 2.4.0*))|\
(Package (% libignition-plugin), $Version (% 1.2.0*))|\
(Package (% libignition-plugin-dev), $Version (% 1.2.0*))|\
(Package (% libignition-rendering3), $Version (% 3.4.0*))|\
(Package (% libignition-rendering3-core-dev), $Version (% 3.4.0*))|\
(Package (% libignition-rendering3-dev), $Version (% 3.4.0*))|\
(Package (% libignition-rendering3-ogre1), $Version (% 3.4.0*))|\
(Package (% libignition-rendering3-ogre1-dev), $Version (% 3.4.0*))|\
(Package (% libignition-rendering3-ogre2), $Version (% 3.4.0*))|\
(Package (% libignition-rendering3-ogre2-dev), $Version (% 3.4.0*))|\
(Package (% libignition-sensors3), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-air-pressure), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-air-pressure-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-altimeter), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-altimeter-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-camera), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-camera-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-core-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-depth-camera), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-depth-camera-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-gpu-lidar), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-gpu-lidar-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-imu), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-imu-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-lidar), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-lidar-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-logical-camera), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-logical-camera-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-magnetometer), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-magnetometer-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-rendering), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-rendering-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-rgbd-camera), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-rgbd-camera-dev), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-thermal-camera), $Version (% 3.0.0*))|\
(Package (% libignition-sensors3-thermal-camera-dev), $Version (% 3.0.0*))|\
(Package (% libignition-tools-dev), $Version (% 1.2.0*))|\
(Package (% libignition-transport8), $Version (% 8.0.0*))|\
(Package (% libignition-transport8-core-dev), $Version (% 8.0.0*))|\
(Package (% libignition-transport8-dbg), $Version (% 8.0.0*))|\
(Package (% libignition-transport8-dev), $Version (% 8.0.0*))|\
(Package (% libignition-transport8-log), $Version (% 8.0.0*))|\
(Package (% libignition-transport8-log-dev), $Version (% 8.0.0*))|\
(Package (% libogre-2.1), $Version (% 2.0.9999~20180616~06a386f-3osrf~*))|\
(Package (% libogre-2.1-dev), $Version (% 2.0.9999~20180616~06a386f-3osrf~*))|\
(Package (% libsdformat9), $Version (% 9.5.0*))|\
(Package (% libsdformat9-dbg), $Version (% 9.5.0*))|\
(Package (% libsdformat9-dev), $Version (% 9.5.0*))|\
(Package (% sdformat9-dbg), $Version (% 9.5.0*))|\
(Package (% sdformat9-doc), $Version (% 9.5.0*))|\
(Package (% sdformat9-sdf), $Version (% 9.5.0*))\
"
