name: lark-parser_xenial
method: http://packages.osrfoundation.org/gazebo/ubuntu-prerelease
suites: [xenial]
component: main
# python packages only, all arches supported
architectures: [amd64, source]
filter_formula: "\
((Package (% =lark-parser) |\
  Package (% =python3-lark-parser) |\
  Package (% =python3-lark-parser-doc)),
  $Version (% 0.7.2-2osrf~xenial))\
"
