name: namniart_armhf_bootstrap
# method: http://packages.namniart.com/repos/ros_support/
method: http://23.239.1.142/repos/ros_support/
suites: [trusty]
component: main
architectures: [armhf]
filter_formula: '(Package (% * ), !Package (% openni2-doc*))'
# needed until we deploy the gpg key
# verify_release: blindtrust
