---
name: opensplice69
method: http://packages.osrfoundation.org/gazebo/ubuntu-stable
suites: [xenial, bionic]
component: main
architectures: [amd64, arm64, source]
filter_formula: Package (% libopensplice69 )
# needed unless we incorporate the right gpg key
verify_release: blindtrust
