name: pyside2
method: http://ppa.launchpad.net/tully.foote/pyside2-reproduction/ubuntu/
suites: [xenial]
component: main
architectures: [i386, amd64, armhf, arm64, source]
filter_formula: "\
((Package (= pyside2) |\
Package (= libpyside-py3-2.0) |\
Package (= libpyside2-dev) |\
Package (= libpyside2.0) |\
Package (= python-pyside2) |\
Package (= python-pyside2-dbg) |\
Package (= python-pyside2.qtconcurrent) |\
Package (= python-pyside2.qtconcurrent-dbg) |\
Package (= python-pyside2.qtcore) |\
Package (= python-pyside2.qtcore-dbg) |\
Package (= python-pyside2.qtgui) |\
Package (= python-pyside2.qtgui-dbg) |\
Package (= python-pyside2.qthelp) |\
Package (= python-pyside2.qthelp-dbg) |\
Package (= python-pyside2.qtnetwork) |\
Package (= python-pyside2.qtnetwork-dbg) |\
Package (= python-pyside2.qtprintsupport) |\
Package (= python-pyside2.qtprintsupport-dbg) |\
Package (= python-pyside2.qtqml) |\
Package (= python-pyside2.qtqml-dbg) |\
Package (= python-pyside2.qtquick) |\
Package (= python-pyside2.qtquick-dbg) |\
Package (= python-pyside2.qtquickwidgets) |\
Package (= python-pyside2.qtquickwidgets-dbg) |\
Package (= python-pyside2.qtscript) |\
Package (= python-pyside2.qtscript-dbg) |\
Package (= python-pyside2.qtsql) |\
Package (= python-pyside2.qtsql-dbg) |\
Package (= python-pyside2.qtsvg) |\
Package (= python-pyside2.qtsvg-dbg) |\
Package (= python-pyside2.qttest) |\
Package (= python-pyside2.qttest-dbg) |\
Package (= python-pyside2.qtuitools) |\
Package (= python-pyside2.qtuitools-dbg) |\
Package (= python-pyside2.qtwebkit) |\
Package (= python-pyside2.qtwebkit-dbg) |\
Package (= python-pyside2.qtwebkitwidgets) |\
Package (= python-pyside2.qtwebkitwidgets-dbg) |\
Package (= python-pyside2.qtwidgets) |\
Package (= python-pyside2.qtwidgets-dbg) |\
Package (= python-pyside2.qtx11extras) |\
Package (= python-pyside2.qtx11extras-dbg) |\
Package (= python-pyside2.qtxml)), \
$Version (% 2.0.0+dev1-1~202102130210~rev1858~pkg5~git131fdfd1~ubuntu16.04.1) |\
((Package (= shiboken2) |\
Package (= libshiboken-py3-2.0) |\
Package (= libshiboken2-dev) |\
Package (= libshiboken2.0)), \
$Version (% 2.0.0.dev0-0~202102130129~rev1610~pkg5~ubuntu16.04.1))\
"
