name: qtsixa
method: http://ppa.launchpad.net/falk-t-j/qtsixa/ubuntu
# For now only import saucy, trusty. PQR have patched versions for openni compatibility
# suites: [lucid, maverick, natty, oneiric, precise, quantal, raring, saucy, trusty]
suites: [saucy, trusty]
component: main
architectures: [i386, amd64, source]
filter_formula: Package (== qtsixa )
