name: vcstool
method: https://packagecloud.io/dirk-thomas/vcstool/ubuntu
suites: [xenial, bionic, focal]
component: main
architectures: [i386, amd64, armhf, arm64, source]
filter_formula: Package (% python3-vcstool, $Version (% 0.2.14*)
